# Adding two Scalars

In [1]:
import theano.tensor as T

In [3]:
from theano import function

In [4]:
x = T.dscalar('x')

In [5]:
y = T.dscalar('y')

In [6]:
z = x + y

In [7]:
f = function([x, y], z)

==========================

In [8]:
f(2, 3)

array(5.0)

In [9]:
f(16.3, 12.1)

array(28.4)

T.dscalar is the type we assign to “0-dimensional arrays (scalar) of doubles (d)”
It is a Theano Type.
dscalar is not a class.
Therefore, neither x nor y are actually instances of dscalar.
They are instances of TensorVariable.
x and y are, however, assigned the theano Type dscalar in their type field

In [10]:
type(x)

theano.tensor.var.TensorVariable

In [11]:
x.type

TensorType(float64, scalar)

In [12]:
T.dscalar

TensorType(float64, scalar)

In [16]:
x.type is T.dscalar

True

You can use the pp function to pretty-print out the computation associated to z.

In [17]:
from theano import pp
print pp(z)

(x + y)


In [18]:
f = function([x, y], z)

The first argument([x,y]) is inputs.
The second argment(z) is output

In [19]:
z.eval({x:16.3, y:12.1})

array(28.4)

# Adding tow Matrices

In [20]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)

In [21]:
f([[1, 2], [3, 4]], [[10, 20], [30, 40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

In [22]:
import numpy
f(numpy.array([[1, 2], [3, 4]]), numpy.array([[10, 20], [30, 40]]))

array([[ 11.,  22.],
       [ 33.,  44.]])

In [37]:
i = T.iscalar('i')
l = T.lscalar('l')
j = T.scalar('j')

In [28]:
i.type

TensorType(int32, scalar)

In [29]:
l.type

TensorType(int64, scalar)

In [38]:
j.type

TensorType(float64, scalar)

In [30]:
a = T.vector()
out = a + a ** 10
f = function([a],out)
print f([0,1,2])

[    0.     2.  1026.]


In [36]:
b = T.vector()
out2 = a**2 + b**2 + 2*a*b
f2 = function([a,b], out2)
print f2([1,2,3],[2,3,4])

[  9.  25.  49.]
